### PR TITLE
Bumps base image version to v24 if tagged this way

### PR DESCRIPTION
**Pull request by bensteinert**
Follow-up PR after merging the ssh_client PR https://github.com/cloutainer/k8s-jenkins-slave-base/pull/1, in case it is fine for you.
Cheers!

### CODE REVIEW

**Comment by clouless** [comment]
ok one sec :D

**Review by clouless — APPROVED** [review]
LGTM

Ok I have just released https://github.com/cloutainer/k8s-jenkins-slave-base/releases/tag/v24 and will wait for jenkins and then merge this as well and tag it :)

**Comment by bensteinert** [comment]
👍 Thanks!

**Comment by clouless** [comment]
@bensteinert ok jenkins has pushed image to DockerHub. You can use `v33` now :)

**Pull request merged**
